from enum import Enum


class MessageRole(str, Enum):
    """
    Enumeration of possible roles for messages in a conversation.

    Attributes:
        SYSTEM: Represents system-level messages, typically used for instructions or context.
        USER: Represents messages sent by the user.
        ASSISTANT: Represents messages sent by the assistant (AI).
        TOOL: Represents messages generated by external tools or functions.
    """

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"
